### ISSUE TITLE
tweaks to libvips build

### ISSUE THREAD

**Issue by jcupitt** [hardpixel/heroku-buildpack-vips#3]
Hi, I have some small suggestions regarding the libvips build in your dockerfile:

```
# libgsf needs libxml2
```

Do you need deepzoom etc. save? I'd be tempted to remove libgsf if users are not demanding it 

```
  libgirepository1.0-dev \
```

This is probably not needed.

```
  libpng-dev \
```

You might not need this.

```
  libjpeg-dev \
```

Maybe verify that you are getting `libjpeg-turbo` at runtime.

```
  libmagickcore-dev
```

I would not include imagemagick. It's much better than it was, but still a large potential attack surface that's not needed unless you want support for formats like BMP.

```
  && meson build --prefix=${VIPS_PREFIX} --libdir=lib \
```

Meson does debug builds by default. Add `--buildtype release` to enable the optimiser.

Could you set `BLOCK_UNTRUSTED`  in the buildpack somehow? I've no idea.

(this is untested and off the top of my head, I'm sure I've made some mistakes)

**Comment by jonian** [comment]
Hi @jcupitt, thank you for your suggestions!

> Do you need deepzoom etc. save? I'd be tempted to remove **libgsf** if users are not demanding it

I'm not sure if anyone needs it, I will keep it for now and consider removing it in the future. Any downside in keeping it except the increased package size?

> This is probably not needed. **libgirepository1.0-dev** 

If I remove it I get an error when building libvips

```
libvips/meson.build:45:4: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake
```
> Maybe verify that you are getting libjpeg-turbo at runtime. **libjpeg-dev**

libjpeg-turbo8 is available at runtime in [heroku stacks](https://devcenter.heroku.com/articles/stack-packages). Should I replace libjpeg-dev with libjpeg-turbo8-dev or just remove it?

I removed `libpng-dev`, `libmagickcore-dev` and added `--buildtype release` to libs that use meson build.

> Could you set BLOCK_UNTRUSTED in the buildpack somehow?

I have a section in the [readme](https://github.com/hardpixel/heroku-buildpack-vips#configuration) that explains how to set the env variable. Do you mean to set it by default?

**Comment by jcupitt** [comment]
> Any downside in keeping it except the increased package size?

No, it's pretty safe I think.

> If I remove it I get an error when building libvips

You can use `-Dintrospection=false` to libvips meson setup to fix this (it ought to be detected automatically really).

>  Do you mean to set it by default?

Yes, for users of your buildpack. Perhaps the readme is enough.

**Comment by jcupitt** [comment]
Also: nice job!

**Comment by jonian** [comment]
Thank you! I implemented the suggestions except removing `libgsf` and setting `BLOCK_UNTRUSTED` by default (added a title in the readme section).
