### ISSUE TITLE
do you plan to support heroku-22 stack?

### ISSUE THREAD

**Issue by MikeKoval** [hardpixel/heroku-buildpack-vips#5]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jonian** [comment]
Hi @MikeKoval, the buildpack already supports heroku-22 stack. Did you have any issues using it with heroku-22?

**Comment by jonian** [comment]
@MikeKoval I fixed the issue. Heroku-22 was not in the detect script.
